config/routes.rb
Rails.application.routes.draw do

  resources :foods
  devise_for :users, :path => '', :path_names => {
    :sign_in => "login",
    :sign_out => "logout",
    :sign_up => "register"
  },
  :controllers => {omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations'}
  resources :users do
    resources :dishes, only: [:show, :index]
    resources :attended_parties, only: [:show, :index]
  end
  resources :parties do
    resources :dishes, only: [:new, :create, :edit, :update]
  end
  post 'parties/:id/dishes/new' => 'dishes#create'
  get '/dishes/most_popular' => 'dishes#most_popular'
  devise_scope :user do
    # using login path for registration
    get '/login' => 'registrations#new'
    post '/signup' => 'registrations#create'
    post '/signin' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
  end
  root 'parties#index'
end

app/controllers/attended_parties_controller.rb
class AttendedPartiesController < ApplicationController
  def show
    @user = User.find(:user_id)
    @party = User.find(params[:party_id])
  end

  def index
    @user = User.find(params[:user_id])
    @attended_parties = @user.attended_parties
    @parties = @attended_parties.nonexpired_parties
    @old_parties = @attended_parties.old_parties
  end
end

app/views/attended_parties/index.html.erb
<h1>Parties attended by <%= @user.name %></h1>
<h2>Upcoming Parties</h2>
<% @parties.all.each do |party| %>
  <h2><%= link_to party.name, party_path(party) %></h2>
  <ul>
    <li>Host: <%= link_to party.host.name, user_path(party.host) %></li>
    <li><%= party.address %></li>
    <li><%= party.display_time %></li>
    <li><%= party.attendees.count %> attendees</li>
  </ul>
<%end%>
<% if @old_parties != [] %>
  <h2>Past Parties</h2>
  <% @old_parties.all.each do |party| %>
    <h2><%= link_to party.name, party_path(party) %></h2>
    <ul>
      <li>Host: <%= link_to party.host.name, user_path(party.host) %></li>
      <li><%= party.address %></li>
      <li><%= party.display_time %></li>
      <li><%= party.attendees.count %> attendees</li>
    </ul>
  <%end%>
<%end%>